name: .NET Core

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x' # You can specify other versions if needed.

    - name: Install dependencies
      run: dotnet restore

    - name: Build the solution
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
